-- Run these commands in your Supabase SQL Editor

-- 1. Create Products Table
CREATE TABLE products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  unit_price REAL NOT NULL,
  category TEXT
);

-- 2. Create Customers Table
CREATE TABLE customers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  email TEXT,
  address TEXT
);

-- 3. Create Bills Table
CREATE TABLE bills (
  bill_id TEXT PRIMARY KEY,
  subtotal REAL NOT NULL,
  tax REAL NOT NULL,
  discount REAL NOT NULL,
  total_amount REAL NOT NULL,
  timestamp TEXT NOT NULL,
  payment_status TEXT NOT NULL,
  payment_method TEXT NOT NULL,
  customer_name TEXT,
  customer_phone TEXT
);

-- 4. Create Bill Items Table
CREATE TABLE bill_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id TEXT NOT NULL REFERENCES bills(bill_id),
  product_id TEXT NOT NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price REAL NOT NULL,
  total_cost REAL NOT NULL
);

-- 5. Seed Initial Products (Optional)
INSERT INTO products (id, name, unit_price, category) VALUES
('p1', 'Milk (1L)', 60, 'Dairy'),
('p2', 'Bread (400g)', 45, 'Bakery'),
('p3', 'Eggs (12pcs)', 90, 'Dairy'),
('p4', 'Rice (1kg)', 80, 'Grains'),
('p5', 'Sugar (1kg)', 50, 'Grains'),
('p6', 'Tea Powder (250g)', 120, 'Beverages'),
('p7', 'Coffee (100g)', 250, 'Beverages'),
('p8', 'Apple (1kg)', 180, 'Fruits'),
('p9', 'Banana (1 doz)', 60, 'Fruits'),
('p10', 'Tomato (1kg)', 40, 'Vegetables');
